# Generated by Django 2.2.6 on 2019-11-27 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_question_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='owner',
        ),
    ]
